### PR TITLE
Fix typos in documentation and examples

### PR DESCRIPTION
**Pull request by yadaiio**
This pull request fixes a few typos with the help of https://github.com/szepeviktor/typos-on-you.

### CODE REVIEW

**Comment by yadaiio** [comment]
Noticed that PHPUnit is failing with an exit code 1 during code coverage. In my opinion, I haven't made any changes to the actual code. Is there something broken on your side or did I do something wrong here?

**Review by clue — COMMENTED** [review]
@yadaiio Thanks for looking into this! I've just filed #84 to fix the unrelated test error. Once this is merged, your changes need to rebased and should be ready to go otherwise. I'll make sure to send a ping your way, unless you beat me to it :shipit:

**Comment by yadaiio** [comment]
After the pull request #84 made by @clue was merged, I rebased this pull request. Thank you so much for putting your effort into this @clue and I'm happy everything's running green now.

**Review by SimonFrings — APPROVED** [review]

**Review by clue — APPROVED** [review]
@yadaiio Thank you for the update, changes LGTM! :shipit:

**Pull request merged**
